[project]
name = "nyaa-rss"
version = "0.1.0"
description = "Fetch RSS from sukebei.nyaa.si and store to MySQL"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests",
    "lxml",
    "pymysql",
]

[tool.black]
line-length = 120
skip-string-normalization = true

[dependency-groups]
dev = []
