CREATE TABLE `fetch_rss` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(500) NOT NULL COMMENT '资源标题',
	`guid` VARCHAR(200) NOT NULL COMMENT '视频网页链接',
	`create_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`update_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	KEY `title` (`title`),
	UNIQUE (`guid`)
) ENGINE = INNODB CHARSET = utf8mb4;
