name: fetch rss to mysql

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */1 * * *'

env:
  host: ${{secrets.host}}
  user: ${{secrets.user}}
  password: ${{secrets.pasword}}
  database: ${{secrets.database}}
  port: ${{secrets.port}}

jobs:
  run_main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]
    steps:
      - uses: actions/checkout@v2.3.3
      - name: install requirement
        run: pip3 install -r requirements.txt
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: run script
        run: python3 ./main.py
